remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: INCOS Environment
description: INcremental COrrect-by-design Specification of variant-rich systems

show_downloads: true
repository_url: https://github.com
